# SPDX-License-Identifier: AGPL-3.0-or-later

"""Move the golden set between its published and its working form.

The working golden set ($JURA_DRIFT_WORK/golden_set.json) holds absolute
paths into the corpus. Those paths name the corpus's source folders and
files, which the repository does not publish, so the committed form,
golden_manifest.json beside this script, holds no paths at all: each image
is identified by its id, class, format, byte count and SHA-256, and a
generated variant also carries the byte count and SHA-256 of the original
it was made from.

    python resolve_golden.py manifest   # working set -> committed manifest
    python resolve_golden.py resolve    # manifest + corpus -> working set

`resolve` walks $JURA_DRIFT_CORPUS, matches originals by size and hash, and
writes the working set with real paths. Variants are then regenerated by
gen_variants.py in the baseline environment, and their hashes must match
the manifest before any comparison means anything.

Standard library only, so it runs under any Python.
"""

import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MANIFEST = os.path.join(HERE, "golden_manifest.json")
WORK = os.path.abspath(
    os.path.expanduser(os.environ.get("JURA_DRIFT_WORK", "~/.cache/jura-drift"))
)
WORKING_SET = os.path.join(WORK, "golden_set.json")
VARIANT_EXT = {"AVIF": ".avif", "HEIC": ".heic", "WEBP": ".webp"}
# Top-level keys that are safe to publish. corpus_root and
# pool_sizes_after_filter stay in the working set only.
PUBLIC_KEYS = ("seed", "min_side_px", "format_counts", "class_counts", "generated_with")


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def to_manifest() -> None:
    with open(WORKING_SET) as fh:
        g = json.load(fh)
    images = []
    for e in sorted(g["images"], key=lambda x: x["id"]):
        m = {
            "id": e["id"],
            "class": e["class"],
            "format": e["format"],
            "generated": e["generated"],
            "sha256": e["sha256"],
            "bytes": e["bytes"],
        }
        if e["generated"]:
            src = e["source_path"]
            m["source_sha256"] = sha256_file(src)
            m["source_bytes"] = os.path.getsize(src)
            m["variant_size"] = e.get("variant_size")
        images.append(m)
    out = {k: g[k] for k in PUBLIC_KEYS if k in g}
    out["images"] = images
    with open(MANIFEST, "w") as fh:
        json.dump(out, fh, indent=1)
        fh.write("\n")
    print(f"wrote {MANIFEST}: {len(images)} images, no paths")


def resolve() -> None:
    corpus = os.environ.get("JURA_DRIFT_CORPUS")
    if not corpus or not os.path.isdir(corpus):
        raise SystemExit("set JURA_DRIFT_CORPUS to the corpus root")
    with open(MANIFEST) as fh:
        m = json.load(fh)

    # (bytes, sha256) of every original the set needs.
    wanted = {}
    for e in m["images"]:
        key = (e["source_bytes"], e["source_sha256"]) if e["generated"] else (e["bytes"], e["sha256"])
        wanted.setdefault(key, []).append(e["id"])
    sizes = {k[0] for k in wanted}

    # The corpus holds byte-identical copies in more than one folder (the
    # training/ tree repeats some originals). Any copy gives the probes the
    # same bytes, but pick deterministically: a copy under the image's own
    # class folder first, then the first in sorted path order.
    matches = {}
    for root, dirs, names in os.walk(corpus):
        dirs.sort()
        for n in sorted(names):
            p = os.path.join(root, n)
            try:
                size = os.path.getsize(p)
            except OSError:
                continue
            if size not in sizes:
                continue
            key = (size, sha256_file(p))
            if key in wanted:
                matches.setdefault(key, []).append(p)
    cls_of = {e["id"]: e["class"] for e in m["images"]}
    found = {}
    for key, paths in matches.items():
        cls = cls_of[wanted[key][0]]
        own = [p for p in paths if os.path.relpath(p, corpus).split(os.sep)[0] == cls]
        found[key] = (own or paths)[0]

    missing = [i for k, ids in wanted.items() if k not in found for i in ids]
    if missing:
        raise SystemExit(f"{len(missing)} originals not found in the corpus: {', '.join(sorted(missing))}")

    images = []
    variants = os.path.join(WORK, "golden", "variants")
    for e in m["images"]:
        w = {k: e[k] for k in ("id", "class", "format", "generated", "sha256", "bytes")}
        if e["generated"]:
            w["source_path"] = found[(e["source_bytes"], e["source_sha256"])]
            w["path"] = os.path.join(variants, e["id"] + VARIANT_EXT[e["format"]])
            w["variant_size"] = e.get("variant_size")
        else:
            w["source_path"] = None
            w["path"] = found[(e["bytes"], e["sha256"])]
        images.append(w)

    out = {k: m[k] for k in PUBLIC_KEYS if k in m}
    out["corpus_root"] = corpus
    out["images"] = images
    os.makedirs(variants, exist_ok=True)
    with open(WORKING_SET, "w") as fh:
        json.dump(out, fh, indent=1)
    print(f"wrote {WORKING_SET}: {len(images)} images resolved from {corpus}")
    print("next: build the environments, then run gen_variants.py in the baseline env")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "manifest":
        to_manifest()
    elif cmd == "resolve":
        resolve()
    else:
        raise SystemExit(__doc__)
