/**
 * Trust Report PDF generation using jsPDF.
 * Client-side only — no server calls, no canvas dependency.
 */

import { jsPDF } from 'jspdf';
import type { VerificationResult } from './types';
import { getTrustLevel } from './types';

export interface ReportMeta {
  fileName: string;
  fileSize: number;
  analysedAt: string;
  analystNote?: string;
  appVersion?: string;
}

const PAGE_WIDTH = 210; // A4 mm
const MARGIN = 15;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;
const LINE_HEIGHT = 5;
const SECTION_GAP = 8;

/** Generate a trust report PDF and return as a Blob. */
export function generateTrustReport(result: VerificationResult, meta: ReportMeta): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const version = meta.appVersion ?? '0.2.0';
  let y = MARGIN;

  function addFooter() {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(120);
      doc.text(
        `Generated by Jura Archive v${version} — Juralabs CIC — Local processing only. No data transmitted.`,
        MARGIN, 287
      );
      doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, 287, { align: 'right' });
    }
  }

  function checkPage(needed: number) {
    if (y + needed > 270) {
      doc.addPage();
      y = MARGIN;
    }
  }

  function heading(text: string) {
    checkPage(12);
    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.setFont('helvetica', 'bold');
    doc.text(text, MARGIN, y);
    y += 6;
    doc.setDrawColor(180);
    doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
    y += 4;
    doc.setFont('helvetica', 'normal');
  }

  function label(text: string) {
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(text, MARGIN, y);
  }

  function value(text: string, xOffset = 45) {
    doc.setFontSize(9);
    doc.setTextColor(40);
    doc.text(text, MARGIN + xOffset, y);
    y += LINE_HEIGHT;
  }

  function row(labelText: string, valueText: string) {
    checkPage(LINE_HEIGHT + 1);
    label(labelText);
    value(valueText);
  }

  function paragraph(text: string, fontSize = 8) {
    checkPage(10);
    doc.setFontSize(fontSize);
    doc.setTextColor(60);
    const lines = doc.splitTextToSize(text, CONTENT_WIDTH);
    doc.text(lines, MARGIN, y);
    y += lines.length * (fontSize * 0.4) + 2;
  }

  // ── Header ──────────────────────────────────────────────────
  doc.setFontSize(16);
  doc.setTextColor(30);
  doc.setFont('helvetica', 'bold');
  doc.text('Jura Archive', MARGIN, y);
  y += 6;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80);
  doc.text('Content Verification Report', MARGIN, y);
  y += 4;
  doc.setFontSize(8);
  doc.text(`Juralabs CIC — ${new Date(meta.analysedAt).toLocaleString('en-GB')}`, MARGIN, y);
  y += SECTION_GAP;

  // ── Summary ─────────────────────────────────────────────────
  heading('Summary');
  const trustPercent = Math.round(result.overallTrust * 100);
  const trustLevel = getTrustLevel(result.overallTrust);
  row('File', meta.fileName);
  row('File Size', formatBytes(meta.fileSize));
  row('Trust Score', `${trustPercent}% (${trustLevel === 'high' ? 'High Trust' : trustLevel === 'medium' ? 'Moderate Trust' : 'Low Trust'})`);
  row('Source Type', result.sourceType);
  row('Content Type', result.contentType);
  if (result.aiGenerator) {
    row('AI Generator', result.aiGenerator);
  }

  if (meta.analystNote) {
    y += 2;
    label('Analyst Note');
    y += LINE_HEIGHT;
    paragraph(meta.analystNote);
  }
  y += SECTION_GAP;

  // ── C2PA Credentials ────────────────────────────────────────
  heading('C2PA Content Credentials');
  if (result.c2paManifest) {
    const m = result.c2paManifest;
    row('Status', m.isValid ? 'Valid' : 'Invalid');
    if (m.claimGenerator) row('Claim Generator', m.claimGenerator);
    if (m.format) row('Format', m.format);
    if (m.title) row('Title', m.title);
    if (m.signedAt) row('Signed At', new Date(m.signedAt).toLocaleString('en-GB'));
    if (m.assertions.length > 0) {
      y += 2;
      doc.setFontSize(8);
      doc.setTextColor(80);
      doc.text(`Assertions (${m.assertions.length}):`, MARGIN, y);
      y += LINE_HEIGHT;
      for (const a of m.assertions) {
        checkPage(LINE_HEIGHT * 2);
        doc.setFontSize(7);
        doc.setTextColor(70);
        doc.text(a.label, MARGIN + 2, y);
        y += 3.5;
        const valLines = doc.splitTextToSize(a.value, CONTENT_WIDTH - 4);
        doc.setTextColor(50);
        doc.text(valLines, MARGIN + 4, y);
        y += valLines.length * 3 + 1;
      }
    }
  } else {
    paragraph('No C2PA Content Credentials found in this file.');
  }
  y += SECTION_GAP;

  // ── EXIF Analysis ───────────────────────────────────────────
  if (result.exifAnalysis) {
    heading('EXIF Analysis');
    const exif = result.exifAnalysis;
    row('Trust Score', `${Math.round(exif.trustScore * 100)}%`);
    row('Fields Populated', `${exif.fieldsPopulated} / ${exif.fieldsTotal}`);
    row('EXIF Present', exif.hasExif ? 'Yes' : 'No');

    if (exif.findings.length > 0) {
      y += 2;
      doc.setFontSize(8);
      doc.setTextColor(80);
      doc.text(`Findings (${exif.findings.length}):`, MARGIN, y);
      y += LINE_HEIGHT;
      for (const f of exif.findings) {
        checkPage(LINE_HEIGHT * 2);
        doc.setFontSize(8);
        doc.setTextColor(f.severity === 'critical' || f.severity === 'high' ? 180 : 60);
        doc.text(`[${f.severity.toUpperCase()}] ${f.title}`, MARGIN + 2, y);
        y += 3.5;
        doc.setTextColor(80);
        const descLines = doc.splitTextToSize(f.description, CONTENT_WIDTH - 4);
        doc.setFontSize(7);
        doc.text(descLines, MARGIN + 4, y);
        y += descLines.length * 3 + 2;
      }
    }
    y += SECTION_GAP;
  }

  // ── Forensic Analysis ───────────────────────────────────────
  const hasForensics = result.elaScore != null || result.noiseScore != null || result.copyMoveScore != null;
  if (hasForensics) {
    heading('Forensic Analysis');

    if (result.elaScore != null) {
      row('ELA Score', `${(result.elaScore * 100).toFixed(1)}%`);
    }
    if (result.noiseScore != null) {
      row('Noise Score', `${(result.noiseScore * 100).toFixed(1)}%`);
    }
    if (result.copyMoveScore != null) {
      row('Copy-Move Score', `${(result.copyMoveScore * 100).toFixed(1)}%`);
    }

    // Embed heatmap images
    const heatmaps: { label: string; data?: string }[] = [
      { label: 'ELA Heatmap', data: result.elaResult?.elaImageBase64 },
      { label: 'Noise Heatmap', data: result.noiseResult?.heatmapBase64 },
      { label: 'Copy-Move Visualisation', data: result.copyMoveResult?.visualisationBase64 },
      { label: 'AI Detection Heatmap', data: result.deepfakeResult?.heatmapBase64 },
    ];

    for (const hm of heatmaps) {
      if (!hm.data) continue;
      checkPage(65);
      doc.setFontSize(8);
      doc.setTextColor(80);
      doc.text(hm.label, MARGIN, y);
      y += 4;
      try {
        doc.addImage(`data:image/png;base64,${hm.data}`, 'PNG', MARGIN, y, CONTENT_WIDTH * 0.7, 55);
        y += 58;
      } catch {
        doc.setFontSize(7);
        doc.setTextColor(120);
        doc.text('(Image could not be embedded)', MARGIN, y);
        y += LINE_HEIGHT;
      }
    }
    y += SECTION_GAP;
  }

  // ── AI Generation Detection ─────────────────────────────────
  if (result.deepfakeResult) {
    heading('AI Generation Detection');
    const df = result.deepfakeResult;
    row('Score', `${(df.score * 100).toFixed(1)}%`);
    row('Confidence', df.confidence);
    row('Suspicious', df.suspicious ? 'Yes' : 'No');

    if (df.watermarks && df.watermarks.length > 0) {
      y += 2;
      doc.setFontSize(8);
      doc.setTextColor(80);
      doc.text('Watermarks detected:', MARGIN, y);
      y += LINE_HEIGHT;
      for (const wm of df.watermarks) {
        checkPage(LINE_HEIGHT);
        row(wm.watermarkType, `${wm.detected ? 'Detected' : 'Not detected'} (${(wm.confidence * 100).toFixed(0)}%)`);
      }
    }

    if (df.signals.length > 0) {
      y += 2;
      doc.setFontSize(8);
      doc.setTextColor(80);
      doc.text(`Signals (${df.signals.filter(s => s.triggered).length} of ${df.signals.length} triggered):`, MARGIN, y);
      y += LINE_HEIGHT;
      for (const s of df.signals) {
        checkPage(LINE_HEIGHT);
        doc.setFontSize(7);
        doc.setTextColor(s.triggered ? 160 : 100);
        doc.text(
          `${s.triggered ? '+' : '-'} ${s.name} (weight: ${s.weight.toFixed(1)})`,
          MARGIN + 2, y
        );
        y += 3.5;
      }
    }
    y += SECTION_GAP;
  }

  // ── Methodology Disclosure ──────────────────────────────────
  heading('Methodology Disclosure');
  const methodologyText = [
    'Error Level Analysis (ELA): Recompresses the image at a fixed JPEG quality and measures pixel-level differences. Regions with inconsistent compression artefacts may indicate editing.',
    'Noise Analysis: Divides the image into blocks and measures variance in each. Inconsistent noise patterns across blocks can indicate splicing or inpainting.',
    'Copy-Move Detection: Uses ORB feature matching to find duplicated regions within the image. Clustered matches suggest content has been cloned from one area to another.',
    'AI Generation Detection: An ensemble of 13 statistical signals analyses frequency spectra, gradient patterns, noise consistency, colour distribution, and other features to estimate the likelihood of AI generation.',
    'EXIF Anomaly Analysis: Checks embedded metadata for consistency, completeness, and known manipulation patterns. Missing or contradictory metadata reduces trust.',
    'C2PA Content Credentials: Verifies cryptographically signed provenance manifests embedded in the file, following the Coalition for Content Provenance and Authenticity specification.',
    'All analysis is performed locally on the user\'s device. No data is transmitted to external servers at any point during the verification process.',
  ];
  for (const text of methodologyText) {
    paragraph(text, 7);
    y += 1;
  }

  // ── Disclaimer ──────────────────────────────────────────────
  y += SECTION_GAP;
  checkPage(15);
  doc.setFontSize(7);
  doc.setTextColor(120);
  const disclaimer = 'This report is generated by automated analysis tools and should be interpreted by qualified professionals. Results are indicative, not conclusive. Jura Archive and Juralabs CIC accept no liability for decisions made based on this report.';
  const disclaimerLines = doc.splitTextToSize(disclaimer, CONTENT_WIDTH);
  doc.text(disclaimerLines, MARGIN, y);

  addFooter();

  return doc.output('blob');
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
