/**
 * Case export ZIP assembly using JSZip.
 * Client-side only — no server calls.
 */

import JSZip from 'jszip';
import type { VerificationResult } from './types';
import { getTrustLevel } from './types';

export interface CaseExportMeta {
  fileName: string;
  fileSize: number;
  exportedAt: string;
  appVersion?: string;
}

/** Assemble a case export ZIP and return as a Blob. */
export async function exportCaseZip(
  result: VerificationResult,
  meta: CaseExportMeta
): Promise<Blob> {
  const zip = new JSZip();
  const version = meta.appVersion ?? '0.2.0';
  const trustPercent = Math.round(result.overallTrust * 100);
  const trustLevel = getTrustLevel(result.overallTrust);

  // ── README.txt ──────────────────────────────────────────────
  const readme = [
    'Jura Archive — Case Export',
    '='.repeat(40),
    '',
    `File: ${meta.fileName}`,
    `File Size: ${formatBytes(meta.fileSize)}`,
    `Exported: ${new Date(meta.exportedAt).toLocaleString('en-GB')}`,
    `Trust Score: ${trustPercent}% (${trustLevel === 'high' ? 'High Trust' : trustLevel === 'medium' ? 'Moderate Trust' : 'Low Trust'})`,
    `Source Type: ${result.sourceType}`,
    `Content Type: ${result.contentType}`,
    '',
    'Contents',
    '-'.repeat(20),
    'report.json          Full verification result as JSON',
    'methodology.txt      Explanation of each analysis technique',
    'heatmaps/            Forensic visualisation images (if available)',
    '',
    'Note: The original source file is not included in this archive.',
    'Tauri desktop applications cannot read arbitrary file paths from the',
    'webview context. To include the source file, add it manually.',
    '',
    `Generated by Jura Archive v${version} — Juralabs CIC`,
    'Local processing only. No data was transmitted to external servers.',
  ].join('\n');

  zip.file('README.txt', readme);

  // ── report.json ─────────────────────────────────────────────
  zip.file('report.json', JSON.stringify(result, null, 2));

  // ── methodology.txt ─────────────────────────────────────────
  const methodology = [
    'Jura Archive — Methodology Disclosure',
    '='.repeat(40),
    '',
    'Error Level Analysis (ELA)',
    'Recompresses the image at a fixed JPEG quality and measures pixel-level',
    'differences. Regions with inconsistent compression artefacts may indicate editing.',
    '',
    'Noise Analysis',
    'Divides the image into blocks and measures variance in each. Inconsistent noise',
    'patterns across blocks can indicate splicing or inpainting.',
    '',
    'Copy-Move Detection',
    'Uses ORB feature matching to find duplicated regions within the image. Clustered',
    'matches suggest content has been cloned from one area to another.',
    '',
    'AI Generation Detection',
    'An ensemble of 13 statistical signals analyses frequency spectra, gradient patterns,',
    'noise consistency, colour distribution, and other features to estimate the likelihood',
    'of AI generation.',
    '',
    'EXIF Anomaly Analysis',
    'Checks embedded metadata for consistency, completeness, and known manipulation',
    'patterns. Missing or contradictory metadata reduces trust.',
    '',
    'C2PA Content Credentials',
    'Verifies cryptographically signed provenance manifests embedded in the file,',
    'following the Coalition for Content Provenance and Authenticity specification.',
    '',
    'All analysis is performed locally on the user\'s device. No data is transmitted',
    'to external servers at any point during the verification process.',
    '',
    'Disclaimer: This report is generated by automated analysis tools and should be',
    'interpreted by qualified professionals. Results are indicative, not conclusive.',
  ].join('\n');

  zip.file('methodology.txt', methodology);

  // ── heatmaps/ ───────────────────────────────────────────────
  const heatmaps: { name: string; data?: string }[] = [
    { name: 'ela.png', data: result.elaResult?.elaImageBase64 },
    { name: 'noise.png', data: result.noiseResult?.heatmapBase64 },
    { name: 'copy_move.png', data: result.copyMoveResult?.visualisationBase64 },
    { name: 'deepfake.png', data: result.deepfakeResult?.heatmapBase64 },
  ];

  const heatmapFolder = zip.folder('heatmaps');
  for (const hm of heatmaps) {
    if (!hm.data || !heatmapFolder) continue;
    // Decode base64 to binary
    heatmapFolder.file(hm.name, hm.data, { base64: true });
  }

  return zip.generateAsync({ type: 'blob' });
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
