/**
 * Case export ZIP assembly using JSZip.
 * Client-side only — no server calls.
 */

import JSZip from 'jszip';
import type { VerificationResult } from './types';
import { getTrustLevel } from './types';
import { DETECTOR_ID_LABELS } from './detectorLabels';

export interface CaseExportMeta {
  fileName: string;
  fileSize: number;
  exportedAt: string;
  appVersion?: string;
}

/** Assemble a case export ZIP and return as a Blob. */
export async function exportCaseZip(
  result: VerificationResult,
  meta: CaseExportMeta
): Promise<Blob> {
  const zip = new JSZip();
  const version = meta.appVersion ?? '0.2.0';
  const trustPercent = Math.round(result.overallTrust * 100);
  const trustLevel = getTrustLevel(result.overallTrust);

  // ── README.txt ──────────────────────────────────────────────
  const readme = [
    'Jura Trace — Case Export',
    '='.repeat(40),
    '',
    `File: ${meta.fileName}`,
    `File Size: ${formatBytes(meta.fileSize)}`,
    `Exported: ${new Date(meta.exportedAt).toLocaleString('en-GB')}`,
    `Trust Score: ${trustPercent}% (${trustLevel === 'high' ? 'High Trust' : trustLevel === 'medium' ? 'Moderate Trust' : 'Low Trust'})`,
    `Source Type: ${result.sourceType}`,
    `Content Type: ${result.contentType}`,
    '',
    'Contents',
    '-'.repeat(20),
    'report.json          Full verification result as JSON',
    'detectors-run.json   Exact detector lineup and pipeline metadata',
    'methodology.txt      Explanation of each analysis technique',
    'heatmaps/            Forensic visualisation images (if available)',
    '',
    'Note: The original source file is not included in this archive.',
    'Tauri desktop applications cannot read arbitrary file paths from the',
    'webview context. To include the source file, add it manually.',
    '',
    `Generated by Jura Trace v${version} — Jura Labs CIC`,
    'Local processing only. No data was transmitted to external servers.',
  ].join('\n');

  zip.file('README.txt', readme);

  // ── report.json ─────────────────────────────────────────────
  zip.file('report.json', JSON.stringify(result, null, 2));

  // ── methodology.txt ─────────────────────────────────────────
  const methodology = [
    'Jura Trace — Methodology Disclosure',
    '='.repeat(40),
    '',
    'Error Level Analysis (ELA)',
    'Recompresses the image at a fixed JPEG quality and measures pixel-level',
    'differences. Regions with inconsistent compression artefacts may indicate editing.',
    '',
    'Noise Analysis',
    'Divides the image into blocks and measures variance in each. Inconsistent noise',
    'patterns across blocks can indicate splicing or inpainting.',
    '',
    'Copy-Move Detection',
    'Uses ORB feature matching to find duplicated regions within the image. Clustered',
    'matches suggest content has been cloned from one area to another.',
    '',
    'AI Generation Detection',
    'An ensemble of 13 statistical signals analyses frequency spectra, gradient patterns,',
    'noise consistency, colour distribution, and other features to estimate the likelihood',
    'of AI generation.',
    '',
    'EXIF Anomaly Analysis',
    'Checks embedded metadata for consistency, completeness, and known manipulation',
    'patterns. Missing or contradictory metadata reduces trust.',
    '',
    'C2PA Provenance',
    'Verifies cryptographically signed provenance manifests embedded in the file,',
    'following the Coalition for Content Provenance and Authenticity specification.',
    '',
    'All analysis is performed locally on the user\'s device. No data is transmitted',
    'to external servers at any point during the verification process.',
    '',
    'Disclaimer: This report is generated by automated analysis tools and should be',
    'interpreted by qualified professionals. Results are indicative, not conclusive.',
  ].join('\n');

  zip.file('methodology.txt', methodology);

  // ── heatmaps/ ───────────────────────────────────────────────
  const heatmaps: { name: string; data?: string }[] = [
    { name: 'ela.png', data: result.elaResult?.elaImageBase64 },
    { name: 'noise.png', data: result.noiseResult?.heatmapBase64 },
    { name: 'copy_move.png', data: result.copyMoveResult?.visualisationBase64 },
    { name: 'deepfake.png', data: result.deepfakeResult?.heatmapBase64 },
  ];

  const heatmapFolder = zip.folder('heatmaps');
  for (const hm of heatmaps) {
    if (!hm.data || !heatmapFolder) continue;
    // Decode base64 to binary
    heatmapFolder.file(hm.name, hm.data, { base64: true });
  }

  // ── detectors-run.json ──────────────────────────────────────
  // Documents the exact detector lineup for this verification so a reviewer
  // can see precisely what ran and reproduce the configuration.
  //
  // Prefer result.detectorsRun (authoritative — written by the Rust backend
  // into the schema v6 `detectors_run` DB column). When absent (legacy case
  // export from a pre-S28-FU1 build), infer from which *Result fields are
  // populated and mark as non-authoritative.
  let exportedDetectorsRun: string[];
  let authoritative: boolean;

  if (result.detectorsRun && result.detectorsRun.length > 0) {
    exportedDetectorsRun = result.detectorsRun;
    authoritative = true;
  } else {
    // Legacy inference — cannot distinguish "ran and returned null" from "never ran"
    authoritative = false;
    exportedDetectorsRun = [];
    if (result.exifAnalysis)                exportedDetectorsRun.push('exif_anomaly');
    if (result.c2paManifest !== undefined)   exportedDetectorsRun.push('c2pa');
    if (result.elaResult)                   exportedDetectorsRun.push('ela');
    if (result.noiseResult)                 exportedDetectorsRun.push('noise');
    if (result.copyMoveResult)              exportedDetectorsRun.push('copy_move');
    if (result.deepfakeResult)              exportedDetectorsRun.push('deepfake');
    if (result.jpegGhostResult)             exportedDetectorsRun.push('jpeg_ghost');
    if (result.segmentedElaResult)          exportedDetectorsRun.push('segmented_ela');
    if (result.colourTemperatureResult)     exportedDetectorsRun.push('colour_temperature');
    if (result.clipResult)                  exportedDetectorsRun.push('clip');
    if (result.watermarkExtractResult)      exportedDetectorsRun.push('watermark');
    if (result.videoDeepfakeResult)         exportedDetectorsRun.push('video_deepfake');
    if (result.transcriptionResult)         exportedDetectorsRun.push('transcription');
    if (result.nprResult)                   exportedDetectorsRun.push('npr');
    if (result.shadowConsistencyResult)     exportedDetectorsRun.push('shadow_consistency');
    if (result.spliceBoundaryResult)        exportedDetectorsRun.push('splice_boundary');
  }

  // Build a filtered label map covering only the detectors that ran
  const detectorIdLabels: Record<string, string> = {};
  for (const id of exportedDetectorsRun) {
    if (DETECTOR_ID_LABELS[id]) {
      detectorIdLabels[id] = DETECTOR_ID_LABELS[id];
    }
  }

  const detectorsRunManifest = {
    authoritative,
    detectorsRun: exportedDetectorsRun,
    mode: result.mode ?? 'standard',
    contentType: result.contentType,
    pipelineVersion: result.methodology?.pipelineVersion ?? version,
    analysedAt: result.methodology?.analysedAt ?? meta.exportedAt,
    detectorIdLabels,
    ...(result.methodology ? { methodology: result.methodology } : {}),
    note: 'Detector ID vocabulary \u2014 stable across builds. Labels may change but IDs are permanent.',
  };

  zip.file('detectors-run.json', JSON.stringify(detectorsRunManifest, null, 2));

  return zip.generateAsync({ type: 'blob' });
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
