# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Jura Trace Sidecar — TF-IDF Knowledge Retriever.

Loads plain-text documents from the knowledge_base/ directory, splits them
into paragraphs, builds a TF-IDF index, and retrieves the most relevant
passages for a given query using cosine similarity.

No external network calls are made.  The entire retrieval pipeline runs
in-process using scikit-learn, which is already a sidecar dependency.

Design choices:
- TF-IDF rather than dense embeddings: no additional model download, no
  dependency on Ollama availability, fast startup, low memory.
- Paragraph-level chunking (double-newline split): preserves semantic units
  from the authored knowledge base documents.
- Minimum passage length of 40 characters: filters section headings and
  separator lines that add noise to the index.
- Lazy initialisation: the TF-IDF matrix is built on first call to
  ``retrieve()``, not at import time, so the sidecar starts up immediately.

Usage:
    from app.services.knowledge_retriever import KnowledgeRetriever

    retriever = KnowledgeRetriever()
    passages = retriever.retrieve("Was this image generated by Stable Diffusion?", top_k=3)
"""

from __future__ import annotations

import logging
import os
import re
from pathlib import Path
from typing import Optional

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

logger = logging.getLogger(__name__)

# Minimum character length for a passage to be indexed.
_MIN_PASSAGE_LENGTH = 40

# Maximum number of passages returned even if caller requests more than exist.
_MAX_TOP_K = 10


def _locate_kb_dir() -> Path:
    """
    Auto-detect the knowledge_base/ directory relative to the sidecar root.

    Looks for the directory in two places:
    1. Relative to this source file: ../../knowledge_base/ (i.e. sidecar/knowledge_base/)
    2. Via the ``JURA_KB_DIR`` environment variable (override for testing/deployment)

    Returns:
        Path to the knowledge_base directory (may not exist yet).
    """
    env_override = os.environ.get("JURA_KB_DIR")
    if env_override:
        return Path(env_override)

    # This file lives at sidecar/app/services/knowledge_retriever.py
    # knowledge_base/ is at sidecar/knowledge_base/
    this_file = Path(__file__).resolve()
    return this_file.parent.parent.parent / "knowledge_base"


def _split_into_passages(text: str) -> list[str]:
    """
    Split a document string into paragraph-level passages.

    Splitting strategy:
    - Primary split on two or more consecutive newlines (paragraph boundary).
    - Each candidate passage is stripped of leading/trailing whitespace.
    - Passages shorter than ``_MIN_PASSAGE_LENGTH`` characters are discarded
      (eliminates section headings like "===========", blank lines, etc.).

    Args:
        text: Raw document text.

    Returns:
        List of passage strings, each representing one paragraph.
    """
    paragraphs = re.split(r"\n{2,}", text)
    return [p.strip() for p in paragraphs if len(p.strip()) >= _MIN_PASSAGE_LENGTH]


class KnowledgeRetriever:
    """
    TF-IDF retriever over a directory of plain-text knowledge base documents.

    The retriever is lazy: documents are loaded and the TF-IDF matrix is
    built on the first call to ``retrieve()`` or ``is_available()``.  All
    subsequent calls reuse the in-memory index.

    Attributes:
        kb_dir: Path to the knowledge_base/ directory.
    """

    def __init__(self, kb_dir: Optional[str] = None) -> None:
        """
        Initialise the retriever.

        Args:
            kb_dir: Optional explicit path to the knowledge base directory.
                    If None, auto-detected relative to the sidecar root.
        """
        self.kb_dir: Path = Path(kb_dir) if kb_dir else _locate_kb_dir()
        self._passages: list[str] = []
        self._sources: list[str] = []  # filename for each passage (for diagnostics)
        self._vectorizer: Optional[TfidfVectorizer] = None
        self._tfidf_matrix = None  # sparse matrix: shape (n_passages, n_terms)
        self._loaded: bool = False

    # ── Loading ───────────────────────────────────────────────────────────────

    def _load(self) -> None:
        """
        Load all .txt files from kb_dir, extract passages, and build the TF-IDF index.

        Called automatically on first use.  Safe to call multiple times — will
        return immediately if already loaded.
        """
        if self._loaded:
            return

        if not self.kb_dir.is_dir():
            logger.warning(
                "Knowledge base directory not found: %s. "
                "Claim verification will fall back to parametric LLM recall.",
                self.kb_dir,
            )
            self._loaded = True  # mark as attempted; won't retry on every call
            return

        txt_files = sorted(self.kb_dir.glob("*.txt"))
        if not txt_files:
            logger.warning(
                "Knowledge base directory %s contains no .txt files. "
                "Claim verification will fall back to parametric LLM recall.",
                self.kb_dir,
            )
            self._loaded = True
            return

        passages: list[str] = []
        sources: list[str] = []

        for path in txt_files:
            try:
                text = path.read_text(encoding="utf-8")
            except OSError as exc:
                logger.warning("Could not read knowledge base file %s: %s", path, exc)
                continue

            file_passages = _split_into_passages(text)
            passages.extend(file_passages)
            sources.extend([path.name] * len(file_passages))
            logger.debug("Loaded %d passages from %s", len(file_passages), path.name)

        if not passages:
            logger.warning("No passages extracted from knowledge base files.")
            self._loaded = True
            return

        # Build TF-IDF index.
        # max_df is set to 1.0 (no ceiling) because the knowledge base is small
        # and curated: there are no genuine stop-word-level terms to filter, and
        # a fractional max_df (e.g. 0.95) would raise ValueError when the corpus
        # is smaller than ~20 passages (0.95 * n < 1 < min_df).
        vectorizer = TfidfVectorizer(
            ngram_range=(1, 2),  # unigrams and bigrams for better phrase matching
            min_df=1,  # keep terms that appear in at least 1 passage
            max_df=1.0,  # no ceiling — preserve all terms in small corpus
            sublinear_tf=True,  # apply log normalisation to term frequencies
            strip_accents="unicode",
            lowercase=True,
        )
        tfidf_matrix = vectorizer.fit_transform(passages)

        self._passages = passages
        self._sources = sources
        self._vectorizer = vectorizer
        self._tfidf_matrix = tfidf_matrix
        self._loaded = True

        logger.info(
            "Knowledge base loaded: %d passages from %d file(s) in %s",
            len(passages),
            len(txt_files),
            self.kb_dir,
        )

    # ── Public interface ──────────────────────────────────────────────────────

    def retrieve(self, query: str, top_k: int = 3) -> list[str]:
        """
        Return the top-k most relevant passages for the given query.

        Relevance is measured by TF-IDF cosine similarity between the query
        and each indexed passage.  Passages are returned in descending order
        of similarity (most relevant first).

        Args:
            query:  The query string (typically a claim or claim + context).
            top_k:  Maximum number of passages to return.  Capped at
                    ``_MAX_TOP_K`` regardless of the caller's request.

        Returns:
            List of passage strings.  May be shorter than top_k if the index
            contains fewer passages, or empty if the knowledge base is not
            available or the query is blank.
        """
        self._load()

        if not query or not query.strip():
            return []

        if self._vectorizer is None or self._tfidf_matrix is None:
            return []

        k = min(top_k, _MAX_TOP_K, len(self._passages))
        if k == 0:
            return []

        try:
            query_vec = self._vectorizer.transform([query.strip()])
            similarities = cosine_similarity(query_vec, self._tfidf_matrix).flatten()
            # argsort ascending; take last k indices (highest similarity)
            top_indices = np.argsort(similarities)[-k:][::-1]
            return [self._passages[i] for i in top_indices if similarities[i] > 0.0]
        except Exception as exc:  # noqa: BLE001
            logger.warning("Knowledge retrieval failed: %s", exc)
            return []

    def is_available(self) -> bool:
        """
        Return True if the knowledge base has been loaded with at least one passage.

        Triggers loading on first call.
        """
        self._load()
        return bool(self._passages)

    @property
    def document_count(self) -> int:
        """Number of distinct source files loaded."""
        if not self._loaded:
            self._load()
        if not self._sources:
            return 0
        return len(set(self._sources))

    @property
    def passage_count(self) -> int:
        """Total number of indexed passages."""
        if not self._loaded:
            self._load()
        return len(self._passages)
