<script lang="ts">
  // Help — Open Source Licences
  // ===========================
  // Satisfies AGPL-3.0 §5(d) "Appropriate Legal Notices" (copyright, no-warranty,
  // licence reference, corresponding-source location) AND reproduces the
  // attribution notices required by the permissive licences of bundled
  // dependencies. The exhaustive per-package texts ship in the repository's
  // THIRD-PARTY-LICENSES.txt (generated by scripts/generate-licenses.sh).
  //
  // Sanctuary theme. British spelling. No emojis. WCAG 2.2 AA.

  const sourceUrl = 'https://codeberg.org/jura-labs/jura-trace';

  // Curated attribution inventory mirrored from THIRD-PARTY-LICENSES.txt.
  const layers = [
    {
      title: 'Rust core engine',
      blurb:
        '876 transitive crates compiled into the desktop binary, overwhelmingly MIT and Apache-2.0. No pure GPL/LGPL/AGPL crates are shipped.',
      items: [
        ['c2pa (c2pa-rs)', 'Apache-2.0 OR MIT', 'Content Authenticity Initiative C2PA library'],
        ['tauri, wry, tao', 'Apache-2.0 OR MIT', 'Desktop shell and webview'],
        ['ring', 'ISC AND MIT AND OpenSSL-style', 'Cryptographic primitives'],
        ['openssl / openssl-sys', 'Apache-2.0', 'TLS and signing chain'],
        ['rusqlite (SQLite)', 'MIT (SQLite: public domain)', 'Local database'],
        ['image, image_hasher, reqwest, serde, tokio, axum', 'MIT OR Apache-2.0', 'Core utilities'],
        ['MPL-2.0 crates (cssparser, selectors, webpki roots, …)', 'MPL-2.0', 'Used unmodified — no source duty'],
      ],
    },
    {
      title: 'SvelteKit frontend',
      blurb: 'Runtime dependencies shipped in the webview bundle. Build-only tooling is excluded.',
      items: [
        ['@tauri-apps/api + plugins', 'MIT OR Apache-2.0', 'Tauri bindings'],
        ['jspdf', 'MIT', 'PDF report export'],
        ['jszip', 'MIT (elected, not GPL-3.0)', 'ZIP evidence bundles'],
        ['dompurify', 'Apache-2.0 (elected)', 'HTML sanitisation'],
        ['html2canvas, canvg, pako, fflate', 'MIT / (MIT AND Zlib)', 'Rendering and compression'],
      ],
    },
    {
      title: 'Python ML sidecar',
      blurb:
        'Only the frozen ONNX/CI build ships. The heavyweight stack (torch, transformers, faster-whisper, open_clip runtime) is excluded and not distributed.',
      items: [
        ['FastAPI, Starlette, Pydantic, Uvicorn', 'MIT / BSD', 'Service layer'],
        ['NumPy, SciPy, scikit-learn, scikit-image', 'BSD-3-Clause', 'Numerics and forensics'],
        ['Pillow', 'HPND (MIT-CMU)', 'Image I/O'],
        ['OpenCV (opencv-python-headless)', 'Apache-2.0', 'Computer vision'],
        ['onnxruntime', 'MIT', 'Model inference'],
        ['pillow-heif (libheif)', 'BSD-3-Clause; libheif/HEVC codecs carry own terms', 'HEIC decode (Linux)'],
      ],
    },
    {
      title: 'ML models and data',
      blurb: 'Detection model weights and the methods they build on.',
      items: [
        ['CLIP ViT-B/32 (OpenCLIP)', 'MIT', 'open_clip; checkpoint laion2b_s34b_b79k — credit LAION'],
        ['BPE vocabulary', 'MIT', 'OpenAI / OpenCLIP'],
        ['UnivFD detection method', 'Cited', 'Ojha, Li & Lee, CVPR 2023'],
        ['GBM classifier + UnivFD probe weights', 'AGPL-3.0-or-later', 'First-party (Jura Labs CIC)'],
      ],
    },
  ] as const;
</script>

<article aria-labelledby="oss-heading">

  <!-- ── Back to Help ──────────────────────────────────────────────────── -->
  <a
    href="/help"
    class="inline-block mb-6 text-sm text-lapis dark:text-lapis-light underline underline-offset-2 hover:no-underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lapis rounded"
  >
    &larr; Help
  </a>

  <!-- ── Page heading ──────────────────────────────────────────────────── -->
  <header class="mb-10">
    <h1
      id="oss-heading"
      class="font-heading text-3xl text-text-light dark:text-quartz mb-4 leading-tight tracking-heading"
    >
      Open Source Licences
    </h1>
    <p class="text-base text-text-light dark:text-quartz leading-relaxed max-w-2xl">
      Jura Trace is free software and is built with open source software. This page
      reproduces the legal notices required by Jura Trace's own licence and by the
      open source components it bundles.
    </p>
    <div class="earth-line mt-6" aria-hidden="true"></div>
  </header>

  <!-- ── AGPL §5(d) Appropriate Legal Notices ──────────────────────────── -->
  <section aria-labelledby="notice-heading" class="mb-12">
    <h2
      id="notice-heading"
      class="font-heading text-2xl text-text-light dark:text-quartz mb-6 leading-tight tracking-heading"
    >
      Jura Trace
    </h2>

    <div class="bg-white dark:bg-graphite rounded-lg border border-border-light dark:border-border-dark p-6 space-y-4">
      <p class="text-sm text-text-light dark:text-quartz leading-relaxed">
        Copyright &copy; 2025&ndash;2026 Paul Griffiths, published by Jura Labs
        Community Interest Company (UK, Companies House 17117467).
      </p>
      <p class="text-sm text-text-light dark:text-quartz leading-relaxed">
        This program is free software: you may redistribute it and/or modify it
        under the terms of the
        <a
          href="https://www.gnu.org/licenses/agpl-3.0.html"
          target="_blank"
          rel="noopener noreferrer"
          class="text-lapis dark:text-lapis-light underline underline-offset-2 hover:no-underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lapis rounded"
          >GNU Affero General Public Licence</a
        >
        as published by the Free Software Foundation, either version 3 or (at your
        option) any later version (AGPL-3.0-or-later). A commercial-licence path is
        available on request.
      </p>
      <p class="text-sm text-text-light dark:text-quartz leading-relaxed font-medium">
        This program is distributed in the hope that it will be useful, but WITHOUT
        ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
        FITNESS FOR A PARTICULAR PURPOSE.
      </p>
      <p class="text-sm text-text-light dark:text-quartz leading-relaxed">
        <strong class="text-text-light dark:text-text-dark">Source code.</strong>
        The complete, buildable source for the released version is published at
        <a
          href={sourceUrl}
          target="_blank"
          rel="noopener noreferrer"
          class="text-lapis dark:text-lapis-light underline underline-offset-2 hover:no-underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lapis rounded break-all"
          >codeberg.org/jura-labs/jura-trace</a
        >.
      </p>
    </div>
  </section>

  <div class="earth-line mb-12" aria-hidden="true"></div>

  <!-- ── Third-party attribution inventory ─────────────────────────────── -->
  <section aria-labelledby="third-party-heading" class="mb-12">
    <h2
      id="third-party-heading"
      class="font-heading text-2xl text-text-light dark:text-quartz mb-6 leading-tight tracking-heading"
    >
      Bundled Open Source Components
    </h2>

    <p class="text-sm text-text-light dark:text-quartz leading-relaxed mb-6 max-w-2xl">
      The components below are distributed inside the application. Build-time-only
      tooling and the heavyweight ML libraries excluded from the shipped sidecar are
      not listed. The exhaustive per-package licence texts and copyright holders are
      reproduced in the
      <code class="text-xs px-1 py-0.5 rounded bg-gray-50 dark:bg-obsidian/60">THIRD-PARTY-LICENSES.txt</code>
      file distributed with the source.
    </p>

    <div class="space-y-6">
      {#each layers as layer}
        <div class="bg-white dark:bg-graphite rounded-lg border border-border-light dark:border-border-dark p-6">
          <h3 class="font-medium text-base text-text-light dark:text-quartz mb-1">{layer.title}</h3>
          <p class="text-xs muted-help leading-relaxed mb-4">{layer.blurb}</p>
          <ul class="space-y-2">
            {#each layer.items as [name, licence, note]}
              <li class="text-sm text-text-light dark:text-quartz leading-relaxed flex flex-col sm:flex-row sm:items-baseline sm:gap-3">
                <span class="font-medium text-text-light dark:text-text-dark sm:flex-none sm:w-2/5">{name}</span>
                <span class="text-xs muted-help sm:flex-none sm:w-1/4">{licence}</span>
                <span class="text-xs muted-help">{note}</span>
              </li>
            {/each}
          </ul>
        </div>
      {/each}
    </div>
  </section>

  <div class="earth-line mb-12" aria-hidden="true"></div>

  <!-- ── Licence texts pointer ─────────────────────────────────────────── -->
  <section aria-labelledby="texts-heading" class="mb-12">
    <h2
      id="texts-heading"
      class="font-heading text-2xl text-text-light dark:text-quartz mb-6 leading-tight tracking-heading"
    >
      Full Licence Texts
    </h2>
    <p class="text-sm text-text-light dark:text-quartz leading-relaxed max-w-2xl">
      The full text of the MIT, BSD-2-Clause, BSD-3-Clause, ISC, zlib, Apache-2.0,
      MPL-2.0, HPND and Unicode-3.0 licences, together with each component's
      copyright holder, is reproduced in
      <code class="text-xs px-1 py-0.5 rounded bg-gray-50 dark:bg-obsidian/60">THIRD-PARTY-LICENSES.txt</code>
      in the source repository. Trademarks, including the C2PA and Content
      Credentials marks, are the property of their respective owners and are not
      licensed by the inclusion of the corresponding software libraries.
    </p>
  </section>

</article>
