#!/usr/bin/env bash
#
# generate-licenses.sh — regenerate the exhaustive third-party licence appendix
# for THIRD-PARTY-LICENSES.txt across all three shipped ecosystems.
#
# Run before cutting a release tag. Requires (installed on demand if missing):
#   - cargo-about      (Rust crate licences + texts)
#   - license-checker  (npm production deps; via npx)
#   - pip-licenses     (frozen Python set; via pip)
#
# The curated summary at the top of THIRD-PARTY-LICENSES.txt is hand-maintained.
# This script only (re)writes the content between the BEGIN/END GENERATED markers.
#
# Usage: bash scripts/generate-licenses.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/THIRD-PARTY-LICENSES.txt"
TMP="$(mktemp)"
GEN="$(mktemp)"

cd "$REPO_ROOT"

echo "==> Rust (cargo-about)"
if ! command -v cargo-about >/dev/null 2>&1; then
  cargo install --locked cargo-about
fi
{
  echo ""
  echo "################################################################################"
  echo "# RUST CRATES (generated by cargo-about)"
  echo "################################################################################"
  echo ""
  # about.toml + about.hbs live in src-tauri/. The template emits one block per
  # crate: name, version, licence, copyright, full licence text.
  cargo about generate --manifest-path src-tauri/Cargo.toml src-tauri/about.hbs
} >>"$GEN"

echo "==> npm production dependencies (license-checker)"
{
  echo ""
  echo "################################################################################"
  echo "# NPM PRODUCTION DEPENDENCIES (generated by license-checker)"
  echo "################################################################################"
  echo ""
  ( cd ui && npx --yes license-checker --production --plainVertical 2>/dev/null )
} >>"$GEN"

echo "==> Python frozen sidecar set (pip-licenses)"
{
  echo ""
  echo "################################################################################"
  echo "# PYTHON SIDECAR (generated by pip-licenses against requirements-ci.txt)"
  echo "################################################################################"
  echo ""
  python3 -m pip install --quiet pip-licenses >/dev/null 2>&1 || true
  # Resolve the frozen set into an ephemeral venv so we attribute exactly what
  # ships, not the dev environment.
  if [ -f sidecar/requirements-ci.txt ]; then
    python3 -m venv /tmp/jura-lic-venv
    /tmp/jura-lic-venv/bin/pip install --quiet -r sidecar/requirements-ci.txt >/dev/null 2>&1 || true
    /tmp/jura-lic-venv/bin/pip install --quiet pip-licenses >/dev/null 2>&1 || true
    /tmp/jura-lic-venv/bin/pip-licenses --format=plain-vertical --with-license-file --no-license-path 2>/dev/null || true
    rm -rf /tmp/jura-lic-venv
  fi
} >>"$GEN"

echo "==> Splicing into $OUT"
# Replace everything between the markers with freshly generated content.
awk -v genfile="$GEN" '
  /<<< BEGIN GENERATED CONTENT/ {
    print
    while ((getline line < genfile) > 0) print line
    skip = 1
    next
  }
  /<<< END GENERATED CONTENT/ { skip = 0 }
  skip != 1 { print }
' "$OUT" >"$TMP"

mv "$TMP" "$OUT"
rm -f "$GEN"
echo "==> Done. Review the diff in $OUT before committing."
